export const options = [
    { value: 'Mumbai', label: 'Mumbai' },
    { value: 'pune', label: 'pune' },
    { value: 'gujrat', label: 'gujrat' },
    { value: 'rajisthan', label: 'rajisthan' },
  ]

  export const secondoptions = [
    { value: 'Mumbai', label: 'Mumbai ' },
    { value: 'Pune', label: 'Pune' },
    { value: 'Nagpur', label: 'Nagpur' },
    { value: 'Nashik', label: 'Nashik' },
    { value: 'VasaiVirar', label: 'VasaiVirar'},
    { value: 'Aurangabad', label: 'Aurangabad' },
    { value: 'Solapur', label: 'Solapur' },
    { value: 'Bhiwandi', label: 'Bhiwandi' },
    { value: 'Amravati', label: 'Amravati'},
    { value: 'Malegaon', label: 'Malegaon' },
    { value: 'Kolhapur', label: 'Kolhapur' },
    { value: 'Sangli', label: 'Sangli' },
    { value: 'Jalgaon', label: 'Jalgaon'},
    { value: 'Akola', label: 'Akola' },
    { value: 'Latur', label: 'Latur' },
    { value: 'Ahmadnagar', label: 'Ahmadnagar' },
    { value: 'Dhule', label: 'Dhule'},
    { value: 'Ichalkaranji', label: 'Ichalkaranji' },
    { value: 'Chandrapur', label: 'Chandrapur' },
    { value: 'Parbhani', label: 'Parbhani' },
    { value: 'Jalna', label: 'Jalna'},
    { value: 'Bhusawal', label: 'Bhusawal' },
    { value: 'Navi', label: 'Navi Mumbai' },
    { value: 'Panvel', label: 'Panvel' },
    { value: 'Bengaluru', label: 'Bengaluru'},
    { value: 'HubballiDharwad', label: 'HubballiDharwad' },
    { value: 'Mysuru', label: 'Mysuru' },
    { value: 'Davangere', label: 'Davangere' },
    { value: 'Mangaluru', label: 'Mangaluru'},
    { value: 'Belagavi', label: 'Belagavi' },
    { value: 'kalburgi', label: 'kalburgi' },
    { value: 'Ballari', label: 'Ballari' },
    { value: 'Vijayapura', label: 'Vijayapura'},
    { value: 'Shimoga', label: 'Shimoga' },
    { value: 'Tumakuru', label: 'Tumakuru' },
    { value: 'Bidar', label: 'Bidar' },
    { value: 'Hospet', label: 'Hospet'},
    { value: 'GadagBetageri', label: 'GadagBetageri' },
    { value: 'Robertsonpet', label: 'Robertsonpet' },
    { value: 'Hassan', label: 'Hassan' }    
  ]

  export const prices = [
    {"from":"Mumbai","to":"Mumbai","price":1000},
    {"from":"Mumbai","to":"Pune","price":2000},
    {"from":"Mumbai","to":"Nagpur","price":3000},
    {"from":"Mumbai","to":"Nashik","price":3000},
    {"from":"Mumbai","to":"Vasai-Virar","price":1000},
    {"from":"Mumbai","to":"Aurangabad","price":2000},
    {"from":"Mumbai","to":"Solapur","price":2000},
    {"from":"Mumbai","to":"Bhiwandi","price":2000},
    {"from":"Mumbai","to":"Amravati","price":2000},
    {"from":"Mumbai","to":"Malegaon","price":2000},
    {"from":"Mumbai","to":"Kolhapur","price":2000},
    {"from":"Mumbai","to":"Nanded","price":2000},
    {"from":"Mumbai","to":"Sangli", "price":2000},
    {"from":"Mumbai","to":"Jalgaon","price":2000},
    {"from":"Mumbai","to":"Akola","price":2000},
    {"from":"Mumbai","to":"Latur","price":2000},
    {"from":"Mumbai","to":"Ahmadnagar","price":2000},
    {"from":"Mumbai","to":"Dhule","price":2000},
    {"from":"Mumbai","to":"Ichalkaranji","price":2000},
    {"from":"Mumbai","to":"Chandrapur","price":2000},
    {"from":"Mumbai","to":"Parbhani","price":2000},
    {"from":"Mumbai","to":"Jalna","price":2000},
    {"from":"Mumbai","to":"Bhusawal","price":2000},
    {"from":"Mumbai","to":"Navi Mumbai", "price":2000},
    {"from":"Mumbai","to":"Panvel","price":2000},
    {"from":"Mumbai","to":"Bengaluru","price":25000},
    {"from":"Mumbai","to":"Hubballi-Dharwad","price":25000},
    {"from":"Mumbai","to":"Mysuru","price":25000},
    {"from":"Mumbai","to":"Davangere","price":25000},
    {"from":"Mumbai","to":"Mangaluru","price":25000},
    {"from":"Mumbai","to":"Belagavi","price":25000},
    {"from":"Mumbai","to":"kalburgi","price":25000},
    {"from":"Mumbai","to":"Ballari","price":25000},
    {"from":"Mumbai","to":"Vijayapura","price":25000},
    {"from":"Mumbai","to":"Shimoga","price":25000},
    {"from":"Mumbai","to":"Tumakuru","price":25000},
    {"from":"Mumbai","to":"Raichur","price":25000},
    {"from":"Mumbai","to":"Bidar","price":25000},
    {"from":"Mumbai","to":"Hospet","price":25000},
    {"from":"Mumbai","to":"Gadag-Betageri","price":25000},
    {"from":"Mumbai","to":"Robertsonpet","price":25000},
    {"from":"Mumbai","to":"Hassan","price":25000},
    {"from":"Mumbai","to":"Bhadravati","price":25000},
    {"from":"Mumbai","to":"Chitradurga","price":25000},
    {"from":"Mumbai","to":"Udupi","price":25000},
    {"from":"Mumbai","to":"Kolar","price":25000},
    {"from":"Mumbai","to":"Mandya","price":25000},
    {"from":"Mumbai","to":"Chikmagalur","price":25000},
    {"from":"Mumbai","to":"Gangavati","price":25000},
    {"from":"Mumbai","to":"Bagalkot","price":25000},
    {"from":"Mumbai","to":"Ranebennuru","price":25000},
    {"from":"Mumbai","to":"Chennai","price":30000},
    {"from":"Mumbai","to":"Coimbatore","price":30000},
    {"from":"Mumbai","to":"Madurai","price":30000},
    {"from":"Mumbai","to":"Salem","price":30000},
    {"from":"Mumbai","to":"Tiruppur","price":30000},
    {"from":"Mumbai","to":"Tiruchirappalli","price":30000},
    {"from":"Mumbai","to":"Vellore","price":30000},
    {"from":"Mumbai","to":"Tirunelveli","price":30000},
    {"from":"Mumbai","to":"Erode","price":30000},
    {"from":"Mumbai","to":"Thoothukkudi","price":30000},
    {"from":"Mumbai","to":"Dindigul","price":30000},
    {"from":"Mumbai","to":"Thanjavur","price":30000},
    {"from":"Mumbai","to":"Hosur","price":30000},
    {"from":"Mumbai","to":"Sivakasi","price":30000},
    {"from":"Mumbai","to":"Karur","price":30000},
    {"from":"Mumbai","to":"Udhagamandalam","price":30000},
    {"from":"Mumbai","to":"Ranipet","price":30000},
    {"from":"Mumbai","to":"Nagercoil","price":30000},
    {"from":"Mumbai","to":"Kanchipuram","price":30000},
    {"from":"Mumbai","to":"Kumarapalayam","price":30000},
    {"from":"Mumbai","to":"Karaikkudi","price":30000},
    {"from":"Mumbai","to":"Neyveli","price":30000},
    {"from":"Mumbai","to":"Cuddalore","price":30000},
    {"from":"Mumbai","to":"Kumbakonam","price":30000},
    {"from":"Mumbai","to":"Tiruvannamalai","price":30000},
    {"from":"Mumbai","to":"Pollachi","price":30000},
    {"from":"Mumbai","to":"Rajapalayam","price":30000},
    {"from":"Mumbai","to":"Gudiyatham","price":30000},
    {"from":"Mumbai","to":"Pudukkottai","price":30000},
    {"from":"Mumbai","to":"Vaniyambadi","price":30000},
    {"from":"Mumbai","to":"Ambur","price":30000},
    {"from":"Mumbai","to":"Nagapattinam","price":30000}
  ]
